global:
  name: consul
  image: consul:1.8.0-beta
  datacenter: dc2
  tls:
    enabled: true

    # Here we're using the shared certificate authority from the primary
    # datacenter that was exported via the federation secret.
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey

  # acls:
  #   manageSystemACLs: true

  #   # Here we're importing the replication token that was
  #   # exported from the primary via the federation secret.
  #   replicationToken:
  #     secretName: consul-federation
  #     secretKey: replicationToken

  federation:
    enabled: true
  # gossipEncryption:
  #   secretName: consul-federation
  #   secretKey: gossipEncryptionKey
connectInject:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: 'NodePort'
    nodePort: 30002
    #annotations: |
    #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    imageEnvoy: envoyproxy/envoy-alpine:v1.13.1
server:
  replicas: 1
  bootstrapExpect: 1
  # Here we're including the server config exported from the primary
  # via the federation secret. This config includes the addresses of
  # the primary datacenter's mesh gateways so Consul can begin federation.
  extraVolumes:
    - type: secret
      name: consul-federation
      items:
        - key: serverConfigJSON
          path: config.json
      load: true









# global:
#   datacenter: dc2
#   image: consul:1.8.0-beta
#   tls:
#     enabled: true
#     caCert:
#       secretName: consul-ca-cert
#       secretKey: tls.crt
#     caKey:
#       secretName: consul-ca-key
#       secretKey: tls.key
#   bootstrapACLs: false
#   federation:
#     enabled: true
#   name: consul

# server:
#   replicas: 1
#   bootstrapExpect: 1
#   extraConfig: |
#     {
#       "primary_datacenter": "dc1",
#       "primary_gateways": ["10.5.1.200:30001"]
#     }
# connectInject:
#   enabled: true
#   imageEnvoy: envoyproxy/envoy-alpine:v1.13.0

# meshGateway:
#   enabled: true
#   enableHealthChecks: false
#   replicas: 1
#   # wanAddress:
#   #   useNodeIP: false
#   #   host: "10.5.2.200"
#   service:
#     enabled: true
#     type: 'NodePort'
#     nodePort: 30002
#     #annotations: |
#     #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
#     imageEnvoy: envoyproxy/envoy-alpine:v1.13.0