global:
  datacenter: dc2
  image: lkysow/consul-ent:1.8.0-beta1-feb21
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key
      secretKey: tls.key
  bootstrapACLs: false
  federation:
    enabled: true
  name: consul

server:
  extraConfig: |
    {
      "primary_datacenter": "dc1",
      "primary_gateways": ["10.5.1.200:1443"]
    }
connectInject:
  enabled: true
  imageEnvoy: envoyproxy/envoy-alpine:v1.13.0

meshGateway:
  enabled: true
  enableHealthChecks: false
  replicas: 1
  wanAddress:
    useNodeIP: false
    host: "10.5.2.200"
  service:
    enabled: true
    type: 'NodePort'
    ports:
      nodePort: 1443
    #annotations: |
    #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    imageEnvoy: envoyproxy/envoy-alpine:v1.13.0
